width: 15
height: 15
depot: [1, 1]
hospitals:
  - [12, 2]
  - [13, 13]
buildings:
  - [5,5]
  - [5,6]
  - [6,5]
  - [10,10]
  - [11,10]
  - [12,10]
initial_fires:
  - [8, 3]
  - [10, 12]
rubble:
  - [7, 7]
  - [7, 8]
  - [8, 7]
survivors: 10
